# .goreleaser.yml
version: 2

builds:
  - binary: gotodo
    main: ./main.go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: gotodo
    repository:
      owner: ethanbao27
      name: homebrew-tap
    commit_author:
      name: goreleaserbot
      email: goreleaser@github.com
    description: "A tiny, delicate todo CLI written in Go"
    homepage: "https://github.com/ethanbao27/gotodo"
    license: "MIT"
    skip_upload: auto
    test: |
      system "#{bin}/gotodo --version"
      system "#{bin}/gotodo --help"
