# .goreleaser.yml
project_name: gotodo
release:
  github:
    owner: ethanbao27
    name: gotodo

builds:
  - id: gotodo
    main: ./main.go
    binary: gotodo
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ tolower .Os }}_{{ tolower .Arch }}"
    files:
      - LICENSE
      - README.md
    wrap_in_directory: true

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
